resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    projects: '**/src/*.csproj'

    restoreDirectory: 'Destination dotNET'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/src/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish

    publishWebProjects: false

    projects: '**/src/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    configuration: 'release'
    packagesToPack: '**/src/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    verbosityPack: 'detailed'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
  artifactName: 'drop' 
  publishLocation: 'Container'


