resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    projects: '**/src/*.csproj'

    restoreDirectory: 'Destination dotNET'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: '**/src/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
          node '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    projects: '**/src/*.csproj'



- task: DotNetCoreCLI@2
  displayName: 'dotnet pack pre'
  inputs:
    command: custom

    projects: 'src/**.*csproj'

    custom: pack

    arguments: '--version-suffix $(versionSuffixForPre) --include-symbols --include-source -o $(Build.ArtifactStagingDirectory)'

    versioningScheme: byEnvVar

    versionEnvVar: versionSuffixForPre

  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack prod'
  inputs:
    command: pack

       condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
       
    projects: 'src/**.*csproj'

    packagesToPack: '**/src/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    verbosityPack: 'detailed'
    



- task: PublishBuildArtifacts@1 
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop 
    publishLocation: container


