resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    projects: '**/src/*.csproj'

    restoreDirectory: 'Destination dotNET'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: '**/src/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish

    publishWebProjects: false

    projects: '**/src/*.csproj'
    arguments: --output $(Build.ArtifactStagingDirectory)


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack pre'
  inputs:
    command: costum
    projects: 'src/**.*csproj'
    costum : pack
     where 'and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master')' 
   node '--version-suffix $(versionSuffixForPre) --include-symbols --include-source'
       
    
    versioningScheme: byEnvVar
    versionEnvVar: versionSuffixForPre

    configuration: 'release'
    packagesToPack: '**/src/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    verbosityPack: 'detailed'


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack prod'
  inputs:
    command: pack
      where and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))'
    projects: 'src/**.*csproj'
    configuration: 'release'
    packagesToPack: '**/src/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    verbosityPack: 'detailed'
    



- task: PublishBuildArtifacts@1 
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop' 
    publishLocation: container


